# Generated by Django 4.2.5 on 2023-09-18 05:16

import base.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_alter_flexiblepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexiblepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.blocks.TextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('full_richtext', base.blocks.RichTextBlock()), ('cards', wagtail.blocks.StructBlock([('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(max_length=80, required=True)), ('text', wagtail.blocks.TextBlock(required=True)), ('button_page', wagtail.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.blocks.URLBlock(help_text='If button above is selected, it will be used first', required=False))])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
